### ISSUE TITLE
BUG: bug reporting mechanism is broken

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#101]
The bug reporting mechanism is broken again.  Need to find a better way =
to send the bug reports.

> Begin forwarded message:
>=20
> From: Google <no-reply@accounts.google.com>
> Subject: Someone has your password
> Date: April 7, 2016 at 9:47:52 AM MDT
> To: myers@ece.utah.edu
>=20
> =09
> Someone has your password=09
> You received this message because myers@ece.utah.edu <> is listed as =
the recovery email for ibiosim@gmail.com <>. If ibiosim@gmail.com <> is =
not your Google Account, click here to disconnect =
<https://accounts.google.com/AccountDisavow?adt=3DAOX8kip4sh1FpYi5FLE52zLu=
n--li8KTlDpClK68TGGnMHOyjgpVgapkgY5FUgs&ree=3D1> from that account and =
stop receiving emails.
> Hi Chris,
> Someone just used your password to try to sign in to your Google =
Account ibiosim@gmail.com, using an application such as an email client =
or mobile device.
> Details:
> Thursday, April 7, 2016 5:47 PM (Central European Summer Time)
> Farum, Denmark*
> Google stopped this sign-in attempt, but you should review your =
recently used devices:
>=20
> REVIEW YOUR DEVICES NOW =
<https://accounts.google.com/AccountChooser?Email=3Dibiosim@gmail.com&cont=
inue=3Dhttps://security.google.com/settings/security/activity?rfn%3D6%26rf=
nc%3D1%26ree%3D1%26asae%3D2>
> Best,
> The Google Accounts team
> *The location is approximate and determined by the IP address it was =
coming from.
> This email can't receive replies. For more information, visit the =
Google Accounts Help Center <https://support.google.com/accounts>.
> You received this mandatory email service announcement to update you =
about important changes to your Google product or account.
> =A9 2016 Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA =
94043, USA

**Comment by buggsley** [comment]
Now brings up web page to verify report is logged.

**Comment by cjmyers** [comment]
Done
