### ISSUE TITLE
BUG: Warnings generated on opening existing BioSim project

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#119]
The following warnings were generated when I opened an existing BioSim
project that had no SBOL file.

WARN  org.jlibsedml.SEDMLReader - Unexpected [Element: <annotation
[Namespace: http://sed-ml.org/sed-ml/level1/version2]/>]
09:41:58 [AWT-EventQueue-0] WARN  org.jlibsedml.SEDMLReader -
Unexpected [Element: <annotation [Namespace:
http://sed-ml.org/sed-ml/level1/version2]/>]
09:41:58 [AWT-EventQueue-0] WARN  org.jlibsedml.SEDMLReader -
Unexpected [Element: <annotation [Namespace:
http://sed-ml.org/sed-ml/level1/version2]/>]
09:41:58 [AWT-EventQueue-0] WARN  org.jlibsedml.SEDMLReader -
Unexpected [Element: <annotation [Namespace:
http://sed-ml.org/sed-ml/level1/version2]/>]
09:41:58 [AWT-EventQueue-0] WARN  org.jlibsedml.SEDMLReader -
Unexpected [Element: <annotation [Namespace:
http://sed-ml.org/sed-ml/level1/version2]/>]
Warning: Could not get charToByteConverterClass!

**Comment by cjmyers** [comment]
Warnings appear to be gone.
