### ISSUE TITLE
BUG: generating SBOL should not overwrite SBOL generated by designer

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#120]
When generating SBOL, need to be careful not to overwrite part created by designer.

**Comment by buggsley** [comment]
During SBML to SBOL generation, should associate generated SBOL with the SBML. 
In subsequent generations, 
this will be the SBOL used and not regenerated.  This also means that if no SBOL
is linked, then the template 
generated should be new.  If it is not new, then designer likely generated it,
so it should not be overwritten.  A new id 
should be generated instead.

**Comment by buggsley** [comment]
At least now does not overwrite and CDs with templates.

**Comment by cjmyers** [comment]
No longer generating templates.  Closing.
