### ISSUE TITLE
FEATURE: Save to new SBOL file when generating a new gene in iBioSim
 version of SBOLDesigner

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#121]
When I create a new gene with promoter, RBS, CDS, and terminator, I would
like a different message or feature to indicate that the new gene model
that I am creating is saving into a new file rather than this message "You
are saving into an existing SBOL file. Would you like to overwrite or
create new versions of parts that already exist in the design." What this
feature currently does is the gene will get save into the default sbol file
of iBioSim and update to a new version of the component. This occurs
because when opening SBOLDesigner in iBioSim, this will create a new
"canvas part information" that will generate a generic form of all the
parts saved in the default sbol file. After adding sequences into the gene
that I am working on, the existing parts stored in the default sbol file of
iBioSim will repudate the version of these parts.

**Comment by buggsley** [comment]
Duplicated on SBOL Designer issue tracker as it involves both programs.

**Comment by cjmyers** [comment]
Please check if you still have an issue with how this works.

**Comment by tramyn** [comment]
SBOLDesigner has the capability to export the user's design to a separate file. However, this still means that the user's design built in SBOLDesigner is still saved in iBioSim's library SBOL file. This feature will not affect the user from exporting their design into another separate SBOL file if the user chooses to do so.
