### ISSUE TITLE
FEATURE: Possible a way to solve our linux issues

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#145]
Begin forwarded message:

> From: "Chris J. Myers" <myers@ece.utah.edu>
> Date: September 6, 2011 7:17:54 AM MDT
> To: group@vlsigroup.ece.utah.edu
> Subject: Possible a way to solve our linux issues
> 
> Hi,
> 
> This looks promising for solving our linux build issues:
> 
> https://build.opensuse.org/
> 
> Chris

**Comment by cjmyers** [comment]
Link does not work anymore.  Closing.
