### ISSUE TITLE
BUG: adding a promoter as a reactant/product/modifier of regular reaction causes problem

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#182]
Adding a promoter into a reaction causes a problem because it does search the promoters when making the layout connection.

**Comment by leandrohw** [comment]
Not sure what the issue is. Currently, promoters are not allowed to connect promoter to reaction.

**Comment by cjmyers** [comment]
I think this relates to the textual view editor.

**Comment by leandrohw** [comment]
I can add promoter to reaction in textual form without errors. Not sure if the problem is this shouldn't be allowed or it was throwing exceptions.

**Comment by cjmyers** [comment]
Ok, will close this one.
