### ISSUE TITLE
BUG: rate rules on concentrations with changing volumes

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#184]
When a rate rule is for a concentration and the volume is changing, the ODE is not being evaluated correctly.  It should be:

d(A/V)/dt = f
d(V)/dt = g

dA/dt = f*V + A*g / V

**Comment by buggsley** [comment]
Done for ODE, should decide if add to Montecarlo.  Here is the code:

    /* Adjust if species rate if compartment size is also changing */
    for (i = 0; i < rec->rulesSize; i++) {
      if (GetRuleType( rec->ruleArray[i] ) == RULE_TYPE_RATE_ASSIGNMENT ) {
	varType = GetRuleVarType( rec->ruleArray[i] );
	j = GetRuleIndex( rec->ruleArray[i] );
	if ( varType == SPECIES_RULE ) {
	  if (!HasOnlySubstanceUnitsInSpeciesNode( speciesArray[j] )) {
	    size = GetCurrentSizeInCompartment( GetCompartmentInSpeciesNode(
speciesArray[j] ) );
	    concentration = GetConcentrationInSpeciesNode( speciesArray[j] );
	    for( k = 0; k < compartmentsSize; k++ ) {
	      compartment = compartmentsArray[k];
	      if (compartment == GetCompartmentInSpeciesNode( speciesArray[j] )) {
		f[j] = f[j] + concentration * f[speciesSize+k];
		break;
	      }
	    }
	  }
	} 
      }
    }

**Comment by leandrohw** [comment]
Passes test suite. Seems to work.
