### ISSUE TITLE
CHANGE: flux bounds and objectives need updating when reaction removed

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#186]
Flux bounds need to be removed when the reactions they refer to are removed.  

Flux objectives should prevent a reaction being removed.

Both need to be properly flattened in our flatten routine.

**Comment by buggsley** [comment]
They also need to be updated when a reaction id is changed.  

Perhaps, we need a method to remove stale flux bounds and objectives.

**Comment by leandrohw** [comment]
I can still remove parameters used in bound and renaming a reaction causes problem.

**Comment by cjmyers** [comment]
You are now prevented from removing parameters used in flux bounds.  However, the message is not being displayed.  You just get a generic message about being in use.  Any idea why this message is not getting forwarded up correct?  @leandrohw 

Also, I cannot cause an issue with rename.  When I rename, it gives an error forcing me to also rename in the bound.  How do you see the issue?

**Comment by cjmyers** [comment]
See variableInUse in SBMLutilities.java.

Need to check every static function is forwarding back error messages correctly.

**Comment by leandrohw** [comment]
Fixed in #478
