### ISSUE TITLE
CHANGE: multiple parameter operators in formula parser

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#187]
> Begin forwarded message:
>=20
> Date: March 25, 2015 at 10:38:57 PM MDT
> Subject: Re: [jsbml-team] Bug in formula parser
> From: Lucian Smith <lucianoelsmitho@gmail.com>
> To: "Chris J. Myers" <myers@ece.utah.edu>
> Cc: Nicolas Rodriguez <rodrigue@ebi.ac.uk>, "jsbml-team@caltech.edu" =
<jsbml-team@caltech.edu>, Leandro Watanabe <leandrohw@gmail.com>, Lucian =
Smith <lpsmith@uw.edu>
>=20
> Well, I literally just this week posted about plans for parsing the =
'chained inequalities'--that syntax used to be legal but nonsensical--if =
you wrote 'a < b < c', it would parse it as '(a < b) < c', which doesn't =
seem like it would ever be useful.  I implemented support for it in SVN, =
and it will be in the upcoming release.
>=20
> The other forms I mentioned are certainly not common, so it's =
understandable if you didn't know they were legal.  That's why I =
mentioned them!
>=20
> (Also, I'm putting some examples of inequalities with 3+ arguments =
into some new tests in the test suite--I'll send them on so you can =
check them out after the next libsbml release.)
>=20
> -Lucian
>=20
> On Wed, Mar 25, 2015 at 8:12 PM, Chris J. Myers <myers@ece.utah.edu =
<mailto:myers@ece.utah.edu>> wrote:
>=20
>> On Mar 25, 2015, at 11:20 AM, Lucian Smith <lucianoelsmitho@gmail.com =
<mailto:lucianoelsmitho@gmail.com>> wrote:
>>=20
>> I should note also that the L3 parser only outputs '=3D=3D', '!=3D', =
'<', '>', '<=3D', and '>=3D' when there are exactly two arguments to the =
function.  When there are 3+, it reverts to the 'eq(a,b,c)' form.
>>=20
>=20
> Hmm, I did not know that was legal.
>=20
>> xor is always output in functional form as 'xor([args])'.
>>=20
>> It's also worth noting that other normally-infix functions such as =
'plus', times', 'and', and others can legally have 0 and 1 arguments:  =
in those cases, the L3 parser outputs "plus()" or "plus(a)", "and()", =
etc.  The test suite has example models of that XML.
>>=20
>> Also, the next release of libsbml will parse chained inequalities =
like this, too:
>>=20
>> a < b < c
>>=20
>> will be parsed as lt(a,b,c) (same with =3D=3D, <, <=3D, >, and >=3D, =
but not !=3D, as that can only ever have two arguments)
>>=20
>> And chained mixed inequalities:
>>=20
>> a < b <=3D c
>>=20
>> are now parsed as
>>=20
>> a<b && b<=3Dc
>>=20
>> to an arbitrary number of arguments:
>>=20
>> a < b <=3D c > d >=3D e =3D=3D f !=3D g
>>=20
>> is parsed as
>>=20
>> and(a<b, b<=3Dc, c>d, d>=3De, e=3D=3Df, f!=3Dg)
>>=20
>> They aren't output as chained inequalities; merely accepted as valid =
input.
>>=20
>=20
> I really did not know those were valid! =20
>=20
> Chris
>=20
>>=20
>> -Lucian
>>=20
>> On Wed, Mar 25, 2015 at 7:39 AM, Nicolas Rodriguez =
<rodrigue@ebi.ac.uk <mailto:rodrigue@ebi.ac.uk>> wrote:
>>=20
>> ok, I have change that. One more question that remain in =
FormulaCompilerLibSBML is how does the libSBML L3 parser
>> output 'xor'?
>>=20
>> Nico
>>=20
>>=20
>> On 03/25/2015 02:09 PM, Chris J. Myers wrote:
>> The L3 compiler in libsbml returns =3D=3D and && and < etc. which is =
my preferred.  Infix looks much better than prefix in my opinion.
>>=20
>> Chris
>>=20
>> Sent from my iPhone
>>=20
>> On Mar 25, 2015, at 8:06 AM, Nicolas Rodriguez <rodrigue@ebi.ac.uk =
<mailto:rodrigue@ebi.ac.uk>> wrote:
>>=20
>> On 03/18/2015 05:16 PM, Andreas Dr=C3=A4ger wrote:
>> Am 16.03.15 um 09:01 schrieb Nicolas Rodriguez:
>> I would propose to change the compiler used by default in
>> 'formulaToString' to be using FormulaCompilerLibSBML which create =
infix
>> compatible
>> with FormulaParserLL3. As for the change to 'parseFormula' we can
>> explain how to get the old behavior.
>> Hi Nico,
>>=20
>> I totally agree. It is confusing for users (and also for test cases) =
if
>> the default formula writer produces output that cannot be identically
>> parsed by the default parser.
>>=20
>> So, please go ahead with this change.
>> So I have now changed the default formula compiler in JSBML.
>>=20
>> One noticeable change is for the comparison operators.
>>=20
>> Now 'eq(x, y)' or 'x =3D=3D y' would be written back by default as =
'eq(x, y)'
>> or 'lt(x, y)' or 'x < y' would be written back by default as 'lt(x, =
y)'
>>=20
>> But in fact, I am not sure what the default LibSBML L3 parser output =
in these cases.
>> It is right or should we output 'x =3D=3D y' and 'x < y' ?
>>=20
>> Thanks,
>> Nico
>>=20
>>=20
>=20
>=20

**Comment by buggsley** [comment]
Probably does not affect us if implemented in the parser and translated to
ASTNodes to match.

**Comment by cjmyers** [comment]
Close
