### ISSUE TITLE
FEATURE: add connection to PRISM for SMC

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#194]
Export PRISM code and run on PRISM or STORM.

**Comment by buggsley** [comment]
Generation of the prism file is now possible with a separate Markov option.  The
property now needs to be 
converted to one PRISM can read and prism needs to be executed.  Also, should
add an option to select 
the command to run prism in the preferences.

**Comment by cjmyers** [comment]
Closing
