### ISSUE TITLE
CHANGE: remove unused array namespace on export

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#196]
If there are no arrays, remove arrays namespace.

**Comment by buggsley** [comment]
Yes. I had these methods to expand every SBase object. You can cast TreeNode to
SBase.

  private static void convert (SBMLDocument doc, Model model, ArraysCompiler
compiler, Map<String, 
ASTNode> idToVector, List<Integer> indices) {
    for (int i = doc.getChildCount() - 1; i >= 0; i--) {
      TreeNode child = doc.getChildAt(i);
      convert(model, child, compiler, idToVector, indices);
    }
  }
  private static void convert(Model model, TreeNode node, ArraysCompiler
compiler, Map<String, 
ASTNode> idToVector, List<Integer> indices) {
    boolean isExpanded;
    for (int i = node.getChildCount() - 1; i >= 0; i--) {
      TreeNode child = node.getChildAt(i);
      isExpanded = expandDim(model, child, compiler.clone(), idToVector,
indices);
      if(!isExpanded) {
        convert(model, child, compiler, idToVector, indices);
      }
    }
  }

Leandro

**Comment by buggsley** [comment]
Would be good if JSBML could remove unused namespace.

**Comment by leandrohw** [comment]
This seems to work on flat models but hierarchical models still keep the arrays namespace when exported as single SBML.

**Comment by cjmyers** [comment]
Done
