### ISSUE TITLE
BUG: validation hangs when checking converted JSBML document

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#198]
In the check function in SBMLutilities, the checkConsistency function hangs if it works on a document that has been converted from a JSBML document.

**Comment by buggsley** [comment]
Seems to be problem with checkConsistency call to web service for comp models.

**Comment by buggsley** [comment]
This should be fixed now.  It was a libsbml validation problem with models with
external model definitions.  
The web service went into an infinite loop.

Chris

**Comment by cjmyers** [comment]
Closing
