### ISSUE TITLE
FEATURE: create implicit arrays

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#199]
Dropping a species, promoter, or reaction into a compartment, the object could inherit the dimensions of the compartment and a straightforward indexing scheme.

Similarly, connections between species and reactions should also inherit dimensions with straightforward indexing.  Same for species and promoters.  This appears to be partially working.

**Comment by buggsley** [comment]
Species connections to reactions could by default add dimensions to the
speciesReference such that the 
number of total dimensions on the reaction and speciesReference is greater or
equal to that of the species.

**Comment by buggsley** [comment]
I've just done a significant refactoring of the array code.  It should now infer
arrays in several instances.  For 
example, if you add an species to an arrayed compartment.  Please check it out
and try adding arrayed objects of 
various types and let me know if you experience any problems.

Thanks,

Chris

**Comment by leandrohw** [comment]
Seems to be working. However, the arrays are not updated when you make modifications to the model. Does iBioSim need to fix the model in case the user modifies something and make the model invalid? For example, if you create an arrayed compartment and drop a species, the implicit array will be inferred. If you remove the arrays from the compartment, the species will still retain the old compartment indices.

**Comment by leandrohw** [comment]
It is fine to create invalid models. It can get quite difficult to ensure the creation of valid arrayed models all the time. Inferring arrays from objects does not need to enforce valid models after adding implicit arrays. Closing this one.
