### ISSUE TITLE
FEATURE: add ability to put SBO term on species for its type

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#200]
Use SBO term to indicate if species is protein, small molecule, RNA, complex, etc.

**Comment by buggsley** [comment]
You can not view/edit SBO terms on many SBML elements, including species.  These
SBO terms are used during 
SBML to SBOL conversion.  They are also used to set the symbols used in the
schematic.

**Comment by cjmyers** [comment]
Closing
