### ISSUE TITLE
BUG - Model Editor not indicating file has changed

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#202]
After editing the Model Editor panel and OK is selected, the working
project file should indicate that the file has been modified with a "*" on
the tab.

Tramy Nguyen

**Comment by buggsley** [comment]
This should be fixed now.  Please test.

**Comment by leandrohw** [comment]
Seems to be working. Made some changes in model editor and '*' showed up on the tab. Closing it.
