### ISSUE TITLE
CHANGE: convert SBOL 1.1 to 2.0

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#203]
On import of SBOL 1.1 file, it should be converted to 2.0.

When opening a project with SBOL 1.1 files, they should be converted to 2.0.

**Comment by buggsley** [comment]
Done

**Comment by tramyn** [comment]
@cjmyers Importing an SBOL 1.1 model is throwing this error in iBioSim and in the online SBOL Validator:

sbol-10105: An SBOL document MUST be serialized as a well-formed RDF/XML file that adheres to the grammar defined by: “https://www.w3.org/TR/rdf-syntax-grammar/” 
Reference: SBOL Version 2.1.0 Section 10 on page 58
Validation failed.

This SBOL 1.1 model was taken from a LacI Inverter model that I created in iBioSim and then exported to SBOL 1.1. 

[iBioSim_issue203.zip](https://github.com/MyersResearchGroup/iBioSim/files/889059/iBioSim_issue203.zip)

**Comment by tramyn** [comment]
Update from testing SBOL 1.1 file:

The iBioSim_issue203.zip file commented above contains invalid xml file. Taken a sample SBOL 1.1 file from libSBOLj was able to successfully import a SBOL 1.1 file into iBioSim.

**Comment by tramyn** [comment]
Current testing:

If the user decides to import an SBOL 1.1 file to iBioSim project, the file will be converted to SBOL 2.0 data model and is stored as iBioSim's project .sbol file. The user can then open this project .sbol file and view the design in SBOLDesigner. 

If the user created an iBioSim project and had sbol file(s) with extension .xml stored within the project directory, iBioSim will throw error when opening up the iBioSim project and mistakenly identified the sbol file as an SBML file.

**Comment by cjmyers** [comment]
Done
