### ISSUE TITLE
CHANGE: SBOL browser should list type and roles for CDs

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#206]
Types should display the type field, if it matches one of the constants, then give short name, else full UR.

If the role is SO type, it should display the Name of that SO term.
	Use SequenceOntology.getName(URI)
If that returns null, display full URI

Also, should display all Types and roles:

Types: <firstType>
           <secondType>
Roles: <firstRole>
           <secondRole>

**Comment by buggsley** [comment]
Needs testing.

**Comment by cjmyers** [comment]
Replacing with SBOLDesigner browser
