### ISSUE TITLE
CHANGE: browser display to include all CD fields

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#207]
Identity:
PersistentIdentity: (if different from identity)
Display Id: (if set)
Version: (if set)
Was derived from: (if set)
Name: (if set)
Description: (if set)
Types: 
Roles: (if set)
Sequence Annotations: (if set)
Sequence: (if set)

Also need to add Annotations, Components, and SequenceConstraints, but they are more involved, will put into separate issue tracker.

**Comment by buggsley** [comment]
Done.  Needs testing.

**Comment by tramyn** [comment]
Two issue discovered during this testing: 

1. SequenceAnnotation for each ComponentDefinition was never set in the SBOL Browser. Try testing with the attached SBOL 2.0 file and look for this ComponentDefinition: http://www.async.ece.utah.edu/BBa_I0462

[BBa_I0462.xml.zip](https://github.com/MyersResearchGroup/iBioSim/files/904205/BBa_I0462.xml.zip)

2. We might want to reconsider renaming the wasDerivedFrom() field to "Was derived from: " in the SBOL Browser. Right now, the wasDerivedFrom() has the text titled "Version: ". This is causing a confusion when I want to compare the SBOL version field from SBOL wasDerivedFrom field.

**Comment by tramyn** [comment]
Update:

SequenceAnnotation is set but it does not have its own text field in SBOL Browser. Instead, the range for SequenceAnnotation is the only property that is expressed within the "Components:" field and is ordered in increasing order. 

<img width="631" alt="screen shot 2017-04-06 at 7 42 38 pm" src="https://cloud.githubusercontent.com/assets/7537729/24782157/b331c190-1b01-11e7-811e-e5e6d7c5317d.png">

**Comment by tramyn** [comment]
@cjmyers Are we still planning on removing SBOL Browser off of iBioSim? If so, what milestone version will this take affect on? Depending on what milestone version you want to make this change, I would like to discuss about the additional features you would like to expand on the browser (i.e. Annotations, Components, and SequenceConstraints for ComponentDefinitions) and whether I should be creating new issues to implement these features.

**Comment by cjmyers** [comment]
I think these functions will be replaced with the browser/editor facilities that we are adapting from SBOLDesigner.  Perhaps, we can discuss this Michael.

**Comment by cjmyers** [comment]
#236
