### ISSUE TITLE
CHANGE: update to libSBML-5.13.0

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#208]
> Begin forwarded message:
>=20
> From: Sarah Keating <skeating@caltech.edu>
> Subject: [sbml-discuss] Release of libSBML-5.13.0
> Date: April 14, 2016 at 3:00:00 AM MDT
> To: LibSBML Development List <libsbml-development@googlegroups.com>, =
SBML Discussion List <sbml-discuss@googlegroups.com>
> Reply-To: sbml-discuss@googlegroups.com
>=20
> ----------------------
> libSBML-5.13.0
> ----------------------
>=20
> We are pleased to announce the release of libSBML-5.13.0 which is
> available for download from
>=20
> https://sourceforge.net/projects/sbml/files/libsbml/5.13.0/
>=20
> =3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D
> 5.13.0 (2016-04-14)
> =3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D
>=20
> STABLE RELEASE
>=20
> * Groups
>=20
>   - The first official version of the specification of Groups
>     is now available, and thus the libSBML code for
>     'groups' is now included in the stable release of libSBML.  This
>     means that all prebuilt binaries for the stable release will
>     include the 'groups' package code. The src archive containing
>     libSBML core code will continue to be available, but there will be
>     additional src archives available in the stable branch: one
>     containing libSBML core plus all stable packages and additional
>     archives of the individual package code.
>=20
>     NOTE: The libSBML GNU make-based build system has not been updated
>           for packages. Thus, to build from src, it is necessary to
>           use the CMake build system.
>=20
>=20
> * New features
>=20
>=20
>   - New functions have been added to the XMLOutputStream to allow the
>     optional XML comment to be further customized.
>=20
>   - The Python binding now includes a __version__ field.
> =09
>   - 'comp' package-specific updates:
>=20
>     - The SBMLResolver interface has been exposed within language =
bindings.
>=20
>   - 'fbc' package-specific updates:
>=20
>     - The MATLAB interface has been expanded to include a dedicated
>       FBC V2 structure.  Thanks to the COBRA Toolbox team for their
>       feedback and testing.
>=20
>     - There was an issue with round-tripping geneProductAssociations
>       between the expression and the infix representation.  This has
>       been sorted.
>=20
>   - 'groups' package-specific updates:
>=20
>     - A function named 'copyInformationToNestedLists' has been
>       added to facilitate keeping information consistent when multiple
>       <group> objects refer to the same thing.
>=20
> * Bug fixes
>=20
>   - Validation was failing to catch when the <piece> element of a
>     <piecewise> had an incorrect number of children.  This has been
>     fixed. Thanks to Jason Zwolak for the report.
>=20
>   - Unit consistency checking was failing to interpret the units of
>     <cn> elements when passed to a <functionDefinition>. This has been =
fixed.
>=20
>   - The getListOfElements code was not being correctly ported to
>     language bindings. This has been corrected.
>=20
>   - Unit consistency checking was failing to correctly handle =
non-integer
>     power expressions. This has been corrected. Thanks to Matthias =
K=C3=B6nig
>     for reporting this.
>=20
>   - The StrictUnitConsistencyValidator has been corrected to identify
>     matching base SI units. Thus, 1000 litre will be correctly equated
>     with 1 metre cubed.
>=20
>   - Sourceforge libSBML Tracker #421: The MATLAB binding was failing
>     to round-trip multi-byte characters used in strings. This has
>     been fixed. Thanks to Will Matern for the report.
>=20
>   - Validation was failing to report that a 'variable' attribute is
>     not permitted on an AlgebraicRule.  This has been corrected.
>=20
>   - Sourceforge libSBML Tracker #418: Using the isnan() function can
>     cause issues with some compilers. LibSBML has a util_isNaN() =
function
>     which should be used when necessary.  Thanks to Alan Garny for
>     reporting this issue.
>=20
>   - The functions that convert an enumeration value to a string had
>     not been ported to language bindings.  This has now been sorted.
>     Thanks to Matthias K=C3=B6nig for letting us know.
>=20
>   - The new ASTNode class instances were failing to deal correctly =
with
>     semantic annotations.  This has been fixed.
>=20
>   - 'comp' package-specific bug fixes:
>=20
>     - Failing to access an external model could cause an endless
>       loop while attempting validation.  This has been corrected.
>       Thanks to Chris Myers for the report.
>=20
>   - 'fbc' package-specific bug fixes:
>=20
>     - Sourceforge libSBML Tracker #419: The converters provided for
>       converting from COBRA style SBML models to SBML+fbc style models
>       were losing a charge of '0' if explicitly set. This has been
>       corrected. Thanks to Ali Ebrahim for reporting the problem.
>=20
>   - 'layout' package-specific bug fixes:
>=20
>     - In some cases the value of the 'id' attribute was being written =
out
>       as the 'name'.  This has been fixed.
>=20
> * Configuration/build system changes
>=20
>   - The Python bindings can now be configured to install using =
setup.py.
>=20
>=20
> * Miscellaneous
>=20
>   - The Python version of libSBML available via PyPi now includes =
binary
>     wheels for Windows and Mac OSX operating systems.
>=20
>   - The Python version of libSBML available via PyPi now includes all
>     dependencies.
>=20
>   - We conducted a review of the mathml-infix parsing code and =
compared
>     inputs and outputs with those of JSBML. This has produced a more
>     synchronized approach between the two APIs.
>=20
>   - There is a known bug in GCC versions 5.1 and 5.2 which results in =
the
>     problem that calling the copy constructor of a base class in the
>     constructor of derived classes produces crashing code.  The =
problem
>     manifests itself in libSBML when using a language binding such as =
the
>     Python interface. Workarounds have been added to the libSBML
>     'Known Issues' documentation.
>=20
>   - Sourceforge libSBML Tracker #417: Documentation was failing to =
write
>     using Python 3.5.  This has been fixed.  Thanks to  Antonio Trande =
for
>     reporting this.
>=20
>=20
> EXPERIMENTAL RELEASE
>=20
> * New features
>=20
>   - 'multi' package-specific updates:
>=20
>     - The code has been updated to reflect v 1.0.6 of the =
specification.
>=20
> =3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D
>=20
> Please report any problems you encounter using libSBML either to the =
mailing list libsbml-team@caltech.edu or using the issue tracker for =
libSBML at
>=20
> https://sourceforge.net/tracker/?group_id=3D71971&atid=3D942737
>=20
> Thanks,
>=20
> the LibSBMLTeam
>=20
> --=20
> You received this message because you are subscribed to the Google =
Groups "sbml-discuss" group.
> To unsubscribe from this group and stop receiving emails from it, send =
an email to sbml-discuss+unsubscribe@googlegroups.com.
> To post to this group, send email to sbml-discuss@googlegroups.com.
> To view this discussion on the web visit =
https://groups.google.com/d/msgid/sbml-discuss/570F5C10.3010801%40caltech.=
edu.
> For more options, visit https://groups.google.com/d/optout.

**Comment by buggsley** [comment]
Updated.  Need to test on Linux and Windows.

**Comment by leandrohw** [comment]
Duplicated. Closing this one.
