### ISSUE TITLE
CHANGE: conversion of SBOL1/GenBank/etc

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#209]
Import SBOL option should convert to SBOL 2.0.
Similarly could allow import of GenBank/FASTA.
Should also be done when opening a project with SBOL 1.1 files.

**Comment by buggsley** [comment]
Works, but it is not really obvious.  Should there be more import/export menu
options?

**Comment by tramyn** [comment]
Tested and working.
