### ISSUE TITLE
BUG: Trying to get the reference for a Biomodel in the import
 Biomodel dialog doesn't work for most models.

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#211]
iBioSim Version 2.8.4

Operating system: Windows 10

Bug reported by: michael13162@gmail.com

Description:
The result is either a page not found or:

[Fatal Error] :16:26: Invalid byte 2 of 3-byte UTF-8 sequence.

**Comment by buggsley** [comment]
This should be fixed.  Please test.

> iBioSim Version 2.8.4
> 
> Operating system: Windows 10
> 
> Bug reported by: michael13162@gmail.com
> 
> Description:
> The result is either a page not found or:
> 
> [Fatal Error] :16:26: Invalid byte 2 of 3-byte UTF-8 sequence.
> 
>

**Comment by leandrohw** [comment]
The "get reference" feature on import BioModel is correctly referencing the corresponding model.
