### ISSUE TITLE
BUG: gilllespie initial output time not working

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#214]
When running a gillespie simulation does not start outputing at the initial output time.

**Comment by buggsley** [comment]
These now work for all reb2sac simulators.  Please implement in the Java-based
ones.

Chris

**Comment by buggsley** [comment]
Make sure all analysis view options are getting to the Java simulators.

**Comment by leandrohw** [comment]
This works in the reb2sac and hierarchical simulators.
