### ISSUE TITLE
CHANGE: Network and Browser options are disabled in anaylsis view

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#215]
iBioSim Version 2.8.4

Operating system: Linux

Bug reported by: l.watanabe@utah.edu

Description:
For the demo iBioSim jar, I cannot select the Network and Browser options.

**Comment by buggsley** [comment]
This was due to missing or non-functional reb2sac / libsbml.

Need to check why this is not working on linux.

**Comment by buggsley** [comment]
Changed how reb2sac/libsbml found.  Is this working now on linux? Please test.

Chris

**Comment by leandrohw** [comment]
This works on linux. Closing this one.
