### ISSUE TITLE
CHANGE: Sort tsd files in analysis view

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#216]
iBioSim Version 2.8.4

Operating system: Linux

Bug reported by: l.watanabe@utah.edu

Description:
When I go to Schematic in Analysis View, when I click on Choose Simulation, the files are not sorted. It is a lot more convenient to sort it out

**Comment by buggsley** [comment]
This should be working now.  Please test.

Chris

**Comment by leandrohw** [comment]
Simulated a model 100 times and the files are now sorted.
