### ISSUE TITLE
CHANGE: update SED-ML file

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#218]
Need to update the SED-ML file when items are deleted, renamed,  or copied.

This goes for models, tasks, and outputs.

Chris

**Comment by buggsley** [comment]
Completed.

**Comment by leandrohw** [comment]
Looks like renaming an analysis view creates a new uniformTimeCourse but retains the old ones.

**Comment by cjmyers** [comment]
Ok, I think I've fixed this one now.  Please test again.

**Comment by leandrohw** [comment]
Renaming analysis view is not deleting plot2D and data generator associated with the old task id.

**Comment by cjmyers** [comment]
Think this works now.  Please test @leandrohw

**Comment by leandrohw** [comment]
Looks good. The older names are being replaced.
