### ISSUE TITLE
BUG: problem with time/t when used in math

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#219]
Using time/t in math is causing an exception.

**Comment by buggsley** [comment]
Should be working now.

Chris

**Comment by leandrohw** [comment]
No exception is thrown when simulating time/t. However, reb2sac ssa generates NaN when you have an assignment rule setting a parameter x = time/t.

**Comment by leandrohw** [comment]
This is working. Closing this one.
