### ISSUE TITLE
CHANGE: save SBOL automatically when saving SBML

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#222]
Should save SBOL automatically when saving SBML file.

Then, can remove from File menu.

**Comment by buggsley** [comment]
Done

**Comment by leandrohw** [comment]
Created a blank project and then created a new model. Started making some changes to the models. The SBOL file associated with the project was updated as the changes in the SBML models were made without the need to manually edit the SBOL file.
