### ISSUE TITLE
CHANGE: Change default name of the file being exported

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#224]
iBioSim Version 2.8.4

Operating system: Linux

Bug reported by: l.watanabe@utah.edu

Description:
When I want to export a file, the default name extension is defaulted to the previously used export method. For example, if I export an sbol file then a pdf file, the default name for export pdf will be file.sbol. Should be file.pdf

**Comment by buggsley** [comment]
I've changed it to only store a default path and not a filename.  This way the
user must always enter a file name and 
removes any confusion when you change between exporting different file types. 
Is this address your problem?  If 
so, please test.

Thanks,

Chris

**Comment by leandrohw** [comment]
Before the change, it would retain the previously used extension even if you want to export a different format. Now the user won't get confused by this.
