### ISSUE TITLE
CHANGE: combine SBOL files in legacy projects

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#225]
When opening a project with multiple SBOL files, merge them into the project library.  Take care with duplicate Id.

**Comment by tramyn** [comment]
2 issues are occurring from this feature:
1. Not all parts from multiple SBOL files are merged into the project library. 
2. When parts are selected to be open in SBOLDesigner, a blank design is brought up. 

Repeat bug by putting these SBOL files in an empty iBioSim project:
[iBioSim_issue225.zip](https://github.com/MyersResearchGroup/iBioSim/files/888999/iBioSim_issue225.zip)

**Comment by tramyn** [comment]
This feature is working now after refreshing iBioSim with a new project workspace.
