### ISSUE TITLE
Use SBOLDesigner's part editor in the place of the SBOL Browser

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#236]
Call the SBOLDesigner part editor when you want to view an SBOL file or associate SBOL to SBML.

**Comment by cjmyers** [comment]
If this works, we can remove the old SBOL Browser.

**Comment by tramyn** [comment]
SBOL Browser has been removed. If in the future we decide to put this feature back into iBioSim, refer to this commit "d3f03ea318224453676496aa6f4cb6591a4ae0c1".
