### ISSUE TITLE
Download Link Not Working

### ISSUE THREAD

**Issue by alfredoalarcon** [MyersResearchGroup/iBioSim#243]
Hello,
No link is working in the official site of iBioSim, I was trying to download it but is impossible.
Maybe a bug in the server?
Thank you,

Alfredo.

**Comment by cjmyers** [comment]
Thanks for catching this.  We migrated our server recently and some files did not make it.  It should be fixed now.

Chris

**Comment by alfredoalarcon** [comment]
Thank you for your fast response, the links are working well now!

Alfredo.

**Comment by cjmyers** [comment]
Great.  Did you by chance submit a bug report from the software?  If so, this uses an old bug manager, which we are no longer using.  We have recently moved to github, but have not had a chance yet to update the software to use the issue tracker.  Please submit your bug view github, if you found one.

Thanks,
Chris

**Comment by alfredoalarcon** [comment]
I haven't been able to install the software since I can't find the Mac version in the official webpage, even if it is described in the installation tutorial. Do you know where I could find it? Or instructions to install the Java version in mac? 
Thank you,
Alfredo.

**Comment by alfredoalarcon** [comment]
Ok, I'll do it if I find any bug! Thank you. Alfredo.

**Comment by cjmyers** [comment]
There is no longer a separate Mac version.  The Java version linked on the website works for all OS.

Chris
