### ISSUE TITLE
Add main functions to SBMLtoSBOL and ModelGenerator

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#254]
Also, might be good to rename them to:

SBML2SBOL
SBOL2SBML

Both should take input file, and "-o" output file.
The SBML2SBOL should take an alternate path for sub-model files.
The SBOL2SBML should take an optional URI for the ModuleDefinition to convert.  If none is provided, then should loop over all rootModuleDefinitions.

**Comment by tramyn** [comment]
@cjmyers : Current commit now supports this functionality:
Provide the following program argument to test:
to run SBML2SBOL: inputFile -I SBML_ExternalPath -o outputFileName
to run SBOL2SBML: inputFile -o outputLocation -u optionalURI

**Comment by cjmyers** [comment]
Done
