### ISSUE TITLE
Preferences should only be accessed from the frontend

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#258]
All backend, conversion, datamodel should get preference values passed into them.

**Comment by tramyn** [comment]
This feature has been implemented. Preferences is a part of frontend and frontend is completely separated from backend and data model. Every time preferences are used in methods, only the frontend will provide the default URIs based on the preferences. This means that backend and data model will retrieve these preferences as parameter values to their functions.
