### ISSUE TITLE
Problem with learn result in tutorial

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#259]
The tutorial figure shows both activation and repression arcs between CI and CII were learned from the data (see the last figure of Section 8 of the system biology tutorial). But I was only able to get the repression arc when I ran GeneNet.

**Comment by zgzn** [comment]
Actually, when I selected multiple runs (1, 3, and 4) from the problem1 folder, it was able to learn the activation arc.
