### ISSUE TITLE
GeneNet (C version) not available for iBioSim 2.9.5 build for Windows & Linux

### ISSUE THREAD

**Issue by zgzn** [MyersResearchGroup/iBioSim#262]
GeneNet under learn view is not available when executing the Windows and Linux scripts of iBioSim 2.9.5. Only the Java version of the GeneNet tool is available, but it does not have the function for user to save the model produced by the learn tool.

**Comment by cjmyers** [comment]
Figure what is needed to setup paths on Windows and linux, make sure this is put into installation documentation.

**Comment by leandrohw** [comment]
Windows' GeneNet seems to be having problems due to a bad executable and not a path issue. Might need to recompile and see if it solves the problem.

**Comment by zgzn** [comment]
@cjmyers @leandrohw Do either of you have access to a Windows and a Linux machine to test this issue? I do not at the moment. Thanks.
