### ISSUE TITLE
Missing DL or DYLD library path setup in "Setting up iBioSim Configurations" tutorial

### ISSUE THREAD

**Issue by zgzn** [MyersResearchGroup/iBioSim#264]
This is not mentioned in the configuration steps, are these paths obsolete? Also, when running iBioSim source on mac with DYLD_LIBRARY_PATH declared in the running environment, a message comes up saying the DDLD_LIBRARY_PATH is missing. What is the difference between DDLD and DYLD? Do we need to set up both for mac these days? Looking at iBioSim.mac64, they point to the same directory.

**Comment by cjmyers** [comment]
MacOS does not pass DYLD_LIBRARY_PATH to application for security reasons.  I hacked a solution using DDLD_LIBRARY_PATH.

**Comment by zgzn** [comment]
I see. I would add a line of instruction on this to the iBioSim github page "Setting up iBioSim Configurations". Otherwise, running iBioSim from Eclipse generates the "DDLD_LIBRARY_PATH is missing" message.

**Comment by leandrohw** [comment]
Done. However, we are missing the directory for the environment variable.

**Comment by leandrohw** [comment]
The lib64 directory is too large to put over here. Users will need to install libSBML on their own. Closing this one.
