### ISSUE TITLE
Java ODE simulators suspend on phage-lambda model

### ISSUE THREAD

**Issue by zgzn** [MyersResearchGroup/iBioSim#271]
iBioSim version: 2.9.5
Model: lambda.xml under iBioSim/docs/SysBioTutorial.

Issues: The Runge-Kutta-Fehlberg (Dynamic) tool flashes a pop-up window, but does not produce any TSD files. Runge-Kutta-Fehlberg (Flatten) and Runge-Kutta-Fehlberg (Hierarchical) suspend their simulation progresses at less than 10%. For short simulation time (like 100), no such issue occurred. For longer time (tested 2100), this issue occurs on both flattened and hierarchical simulators.

**Comment by leandrohw** [comment]
This seems to work on the Runge-Kutta-Fehlberg (Flatten) and Runge-Kutta-Fehlberg (Hierarchical) simulators now.

**Comment by leandrohw** [comment]
It works now. Closing.
