### ISSUE TITLE
Refactor backend

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#281]
Let’s organize into 3 groups around the 3 tools.  Namely, let’s refactor verification under analysis.  I’m planning to update the analysis tool to allow it to access verification.  Also, let’s move sbol under synthesis.  This is the old assembly code and may largely get removed soon.

**Comment by tramyn** [comment]
@cjmyers This change is done and is ready for merging with the master branch.

**Comment by leandrohw** [comment]
Merged.
