### ISSUE TITLE
Limit Associate SBOL in iBioSim

### ISSUE THREAD

**Issue by tramyn** [MyersResearchGroup/iBioSim#289]
Remove Associate SBOL in reaction editor, event, rule... etc. and only limit to Model and Species editor.

**Comment by tramyn** [comment]
Update: removed associate SBOL in reaction editor, event editor, parameter editor, promoter editor, and rule editor

**Comment by cjmyers** [comment]
Re-added to Promoter editor

**Comment by cjmyers** [comment]
Done
