### ISSUE TITLE
Update SBML Species after an SBOL Association

### ISSUE THREAD

**Issue by tramyn** [MyersResearchGroup/iBioSim#291]
If the user decides to associate an SBOL part, then the SBML id, name and SBO term should be set based upon SBOL part the user is trying to associate to. However, if the user does not associate an SBOL part to the SBML model or species, then make sure that whatever save button that appears in the species panel gets highlighted to allow the user to make changes to the specified species.

**Comment by tramyn** [comment]
@cjmyers When associating parts to an SBML element, do we want to map the following fields from the SBOL part editor to SBML Editor?

SBOL  Display Id -> SBML Id
SBOL  Name -> SBML name

**Comment by cjmyers** [comment]
Yes.

And the type to SBO term

**Comment by tramyn** [comment]
@cjmyers When I get a componentDefinition to associate to an SBML species, I get an Illegal URI exception because the ComponentDefinition part does not have the correct prefix when getting the ComponentDefinition's type. After checking the SBOL 2 specification, it looks like all SBOL ComponentDefinition types, return BioPAX URI. 

For example:
http://www.biopax.org/release/biopax-level3.owl#DnaRegion
http://www.biopax.org/release/biopax-level3.owl#Protein

**Comment by cjmyers** [comment]
Where are you getting this exception?  What you should be doing is checking if the CD’s type you just fetched is of DNA type, then map that to the corresponding SBO term on the Species (i.e., DNA segment SBO:0000634), similarly if it is an RNA type it is an RNA segment, protein is a polypeptide chain, etc.  The complete mapping is at line 397 of your SBML to SBOL converter code.

**Comment by tramyn** [comment]
@cjmyers Ooooh I got it. Understood.

**Comment by tramyn** [comment]
Update: 
- SBML id, name, and SBO term is updated after associating SBOL for species. 
- SBML id and name is updated after associating SBOL for Model. However, SBO terms for SBML model has not been set. I still need to determine the mapping for the SBOL SBO term to the equivalent SBML SBO term.

**Comment by cjmyers** [comment]
There is no mapping from ModuleDefinition to the SBO term we use on the SBML Model, so don’t worry about this.
