### ISSUE TITLE
Change SBOL namespace of an annotated SBOL part

### ISSUE THREAD

**Issue by tramyn** [MyersResearchGroup/iBioSim#293]
Two  options for this feature:
1. copy the SBOL into your namespace and change local copy
2. dissociate SBOL part entirely. 

If the user associated an SBML species or SBML model with an SBOL part (whether it be a local part the user created or from the registry) then the SBML element id, name and SBO term is set. If the user decide to make modification to the SBOL associated part (i.e. name) and the user then save the modified part, then take that SBOL associated part by changing the namespace of the SBOL part to the local namespace before changing the part. 

Another option is to dissociate the SBOL part entirely from the SBML species or model. 

This issue pairs with #292 to dissociate an SBOL part.

**Comment by cjmyers** [comment]
Remove current association.
Copy into users URI prefix space, the original SBOL that was linked.
Associate this copy to the object.

**Comment by tramyn** [comment]
Since this issue is a duplicate of #292 , this issue will be closed.
