### ISSUE TITLE
Load SBOL parts designed in SBOLDesigner to Goksel's Model Generator

### ISSUE THREAD

**Issue by tramyn** [MyersResearchGroup/iBioSim#295]
Call Goksel's model generator by loading parts that the user designed in SBOLDesigner. During this phase, the model generator will attempt to find ComponentDefinition(s) that will help inhibit, activate, and/or produced the user's part design that was updated to the model generator.

**Comment by cjmyers** [comment]
Click on SBOL library to execute model generator instead.
