### ISSUE TITLE
Importing SBOL 1.1 file

### ISSUE THREAD

**Issue by tramyn** [MyersResearchGroup/iBioSim#302]
Currently, iBioSim will allow the user to import an SBOL file into the project workspace and store the SBOL data model into iBioSim's .sbol library file. At this timeframe, iBioSim should have converted the imported SBOL file and generated an SBML model from it and showcase the SBML model on the project workspace. However, the SBML model that should've been generated will only work for SBOL 2.0 files but not for SBOL 1.x files. To resolve this issue, make sure to check what version of the SBOL document the user has imported and convert them to 2.0 file before converting the SBOL document to an SBML model.  

Try testing with this SBOL 1.1 data model on a new iBioSim project workspace.
[BBa_I0462.xml.zip](https://github.com/MyersResearchGroup/iBioSim/files/903686/BBa_I0462.xml.zip)

**Comment by cjmyers** [comment]
An SBOL1 file has no ModuleDefinitions, so the SBOL to SBML converter will not convert anything to a Model.  Namely, only ModuleDefinitions make sense to convert to models. 

Chris

**Comment by tramyn** [comment]
@cjmyers That's true! In this case, it would be nice to report a message to the user to indicate that an SBOL 1.1 file was detected and no SBOL to SBML conversion will take place. Another option is to log it to the dialog box at the bottom of the GUI.

**Comment by cjmyers** [comment]
A popup window is likely to be noticed more.  However, I’m not sure it is an error.  When you import SBOL, it copies the SBOL objects into the project SBOL file.  If, there are ModuleDefinitions, it also runs the SBOL to SBML converter.  In the future, we may also produce models without ModuleDefinitions using Goksel’s utility.  Actually, the output of Goksel’s utility when no interactions is found should still be an empty ModuleDefinition that includes each ComponentDefinition.  Perhaps, we would still generate a Model in this case, albeit not a very interesting one as it would just include a single annotated species.

**Comment by cjmyers** [comment]
Message should state how many ComponentDefinitions are added to the local SBOL library and how many ModuleDefinitions are converted into SBML files.

**Comment by tramyn** [comment]
Update: This is done.
