### ISSUE TITLE
Add support for L3V2

### ISSUE THREAD

**Issue by leandrohw** [MyersResearchGroup/iBioSim#311]
Need to add support for L3V2 in Java simulators.

**Comment by cjmyers** [comment]
Only for Java simulator from command line for 3.0, full support in 3.1.

**Comment by cjmyers** [comment]
If arrays require L3V2, then we will need to move iBioSim completely to L3V2.  This means all models created will be L3V2 and all models imported or opened will need to be converted to L3V2.

**Comment by cjmyers** [comment]
To support L3V2 in simulation:
1) Check for null on everything
2) RateOf
3) Min and Max
4) Implies
5) Integers can be treated like Booleans

**Comment by cjmyers** [comment]
I think this working in the GUI.  Booleans though could be simplified, if we want.  Will log a new issue.
