### ISSUE TITLE
Data not available for histogram after simulation on linux v 2.9.5 

### ISSUE THREAD

**Issue by zgzn** [MyersResearchGroup/iBioSim#318]
After simulating the lambda model (attached) with either ODE or SSA (only Java simulators), clicking on histogram does not bring up the data to view. However, TSD graphs were created. This seems to happen on the linux version, not the mac version. 

[SysBioTutorial.zip](https://github.com/MyersResearchGroup/iBioSim/files/914745/SysBioTutorial.zip)

**Comment by cjmyers** [comment]
Java simulators need to output data for the histograms.

**Comment by cjmyers** [comment]
duplicate
