### ISSUE TITLE
README run configuration isn't valid

### ISSUE THREAD

**Issue by michael13162** [MyersResearchGroup/iBioSim#337]
I am only able to get iBioSim to run if I set Project to "frontend" and Main class to "edu.utah.ece.async.frontend.main.Gui".  This is different from what the README instructions say.  

Update: I just pulled and now the project can't be found.  When I set project to "frontend", there are no main classes found either.

**Comment by cjmyers** [comment]
We changed the name from frontend to gui.  Instructions on README look correct.  You might need to reimport your project.

Chris

**Comment by cjmyers** [comment]
close
