### ISSUE TITLE
Generate model over all SBOL files

### ISSUE THREAD

**Issue by tramyn** [MyersResearchGroup/iBioSim#340]
Provide option to allow user to generate model over all SBOL files when right clicking on sbol library.
<img width="276" alt="screen shot 2017-04-30 at 5 36 10 pm" src="https://cloud.githubusercontent.com/assets/7537729/25569016/872fd83e-2dcb-11e7-8266-588fcacaba40.png">

**Comment by tramyn** [comment]
This feature should be removed and can technically be performed from the issue reported in #354. 

@cjmyers When you approve the new feature that is now supported in issue #354, we can remove this feature from this issue.

**Comment by cjmyers** [comment]
Agree that 354 replaces this one.
