### ISSUE TITLE
Updated SBML Test Suite

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#343]
As part of our continuing effort to improve SBML exchange and uptake, we have developed a large number (over 550!) new tests for the SBML Test Suite, currently available in the 'develop' branch of the SBML Test Suite on github:

https://github.com/sbmlteam/sbml-test-suite/tree/develop

or, more specifically:

https://github.com/sbmlteam/sbml-test-suite/tree/develop/cases/semantic

At this point, I need your help to finalize these tests!  The majority have been tested with a simulator that has at least partial support for l3v2 models, but several tests (particularly those involving algebraic rules and/or the csymbol 'delay') have only been tested 'by eye', as it were.  As such, some test results have not yet been validated: if your simulator covers those test cases and you can confirm (or deny) that the results are accurate, I'd love to hear from you.

In addition to testing the new l3v2 constructs and situations, we also performed an extensive search for pairs of test tags that had not been covered in the suite before now, leading to the addition of a wide variety of tests that check unusual combinations of SBML elements.  A summary of those tests (along with all the current changes) are available at

https://github.com/sbmlteam/sbml-test-suite/blob/develop/NEWS.md

If anyone has questions about any of the new tests, I'm more than happy to discuss them.  I will also be available at HARMONY in June for additional feedback.

Thank you!

-Lucian Smith

**Comment by leandrohw** [comment]
Need to fix the following for the java simulator:

 00028 00950 00951 00967 01306 01507 01508 01510 01511

28 has discontinuity so I'm just a little off at the discontinuous point
950,951 are due to NaN
967 my script fails because the printing time is a little off and I skip one point but the test suite doesn't complain about it.
1306 I have implemented the fix for this but need to merge
1507 1508 1510 1511 event + volume concentration

**Comment by leandrohw** [comment]
The new test suite was used to test the simulators. More specific issues for the bugs found were created. Might need to document the ones that reb2sac fail. Nonetheless, closing this one.
