### ISSUE TITLE
Replace vpr jar by using the individual jar files for dependencies

### ISSUE THREAD

**Issue by tramyn** [MyersResearchGroup/iBioSim#345]
Replace current vpr-withDependencies.jar with the individual jar files for dependencies.

**Comment by tramyn** [comment]
Update: 
- Moved dependencies used in vpr jar to iBioSim conversion pom file. 
- Removed vpr-data with dependencies and replaced it with vpr-data without dependencies into iBioSim lib directory. 
- I've put the dependencies jars (vpr-sbol-util and vpr-rdf-util) as local dependencies because these jars are not available to maven central.

**Comment by cjmyers** [comment]
Closing
