### ISSUE TITLE
ODE simulators stuck on this example

### ISSUE THREAD

**Issue by zgzn** [MyersResearchGroup/iBioSim#350]
I am not sure if this is a bug. But rkf45 and Runge-Kutta (Flatten) both stuck without making progress on the attached example, and no errors are reported either. It looks like an issue with the model, but I do not know how I can locate it in the model. 

[FinalProj.zip](https://github.com/MyersResearchGroup/iBioSim/files/991505/FinalProj.zip)

**Comment by zgzn** [comment]
I removed all reversed complex formation reaction arcs from the model, rkf45 slowly finished the simulation, but Runge-Kutta (Flatten) stuck at 50%. Attached is the SBML model. 

[EColi_fix.xml.zip](https://github.com/MyersResearchGroup/iBioSim/files/991559/EColi_fix.xml.zip)

**Comment by cjmyers** [comment]
Need to check if slow or stuck.

**Comment by leandrohw** [comment]
Seems the new ODE simulator fixed this issue. Closing
