### ISSUE TITLE
Provide option to select design for model generation

### ISSUE THREAD

**Issue by tramyn** [MyersResearchGroup/iBioSim#354]
Have current model generator bring up an option to allow user to decide which design they would like to have SBOL interactions to be constructed on rather than sending the entire SBOL library file.

**Comment by tramyn** [comment]
Update: User now has the option to 
- perform VPR Model Generation on all SBOL ComponentDefinition within an SBOL file 
- perform VPR Model Generation on a specified ComponentDefinition within an SBOL file

**Comment by tramyn** [comment]
Update: Modify VPR Model Generation so user can have option to select more than one genetic design to perform on. To do so, create a window similar to RootInputDialog from SBOLDesigner and allow user to select from RootModuleDefinition and RootComponentDefinition designs.

Side note: 
- Calling VPR on RootModuleDefinition will add more information (i.e. interactions) to the current ModuleDefinition. 
- Calling VPR on RootComponentDefinition will add Interactions and ModuleDefinition to given RootComponentDefinition.

**Comment by tramyn** [comment]
Update: User can now select multiple designs to either open in SBOLDesigner or generate VPR model. Filtering designs are added during this phase to restrain user from generating VPR model if ModuleDefinitions design are selected. SBOLDesigner is only allowed to be open for ComponentDefinitions.

**Comment by tramyn** [comment]
@cjmyers 2 clarifications:
1. So show ComponentDefinition and show ModuleDefinition can never be selected at the same time?
2. what does group radio button mean? Is grouping a radio button something similar to a on/off slider?

**Comment by cjmyers** [comment]
Correct never on at the same time.  This is what a radio button means.  To group them, you use button group like this:

   ButtonGroup abstractionButtons = new ButtonGroup();
    abstractionButtons.add(noAbstraction);
    abstractionButtons.add(expandReactions);
    abstractionButtons.add(reactionAbstraction);
    abstractionButtons.add(stateAbstraction);

When you group buttons, you are saying these form a radio button group in which ONLY one can be selected at a time.

**Comment by cjmyers** [comment]
Make sure that ComponentDefinitions and Show only Root are enabled by default.  

Please also reverse the selection buttons.  I believe we always have Cancel on left and default selection on right.  This would be mean:

"Cancel", "Generate Model", "Open in SBOLDesigner" with "Open in SBOLDesigner" the default.

**Comment by cjmyers** [comment]
Give error message if no design is selected.

**Comment by cjmyers** [comment]
Done.
