### ISSUE TITLE
Allow user to select which synbiohub repository to perform VPR

### ISSUE THREAD

**Issue by tramyn** [MyersResearchGroup/iBioSim#355]
Right now, the VPR model generator is hardcoded to use a specified synbiohub repository. We want to allow the user the capability to select which synbiohub repository the user can connect their design to perform VPR model generation on. This window should pop up after the user has indicated they want to perform VPR model generation. Once the window pops up, provide a listing repository the user can select from for the VPR model generation to connect to as its endpoint. 

Note that these listing of repository is taken from iBioSim's Preferences. 

This pop up window should look something like the following:
<img width="638" alt="screen shot 2017-05-17 at 1 21 37 pm" src="https://cloud.githubusercontent.com/assets/7537729/26172053/44f4c0ec-3b04-11e7-86e3-8272a76fd9c4.png">

**Comment by tramyn** [comment]
Done. This feature should pop up when the user double click on the .sbol library file.

**Comment by cjmyers** [comment]
Closing.
