### ISSUE TITLE
Add button to remove SBOL association

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#358]
Add button to the right of "Add/Edit SBOL Association" to "Remove SBOL Association".

**Comment by tramyn** [comment]
Update: A button has been added for "Remove SBOL Association" but still need to implement code to actually remove SBOL association for SBOL annotation off of SBML elements.

**Comment by cjmyers** [comment]
If there is an SBOL annotation to remove, open a dialog to confirm that they want to remove that annotation.  Show the URI of the annotation you are removing OR better yet the Name or DisplayId.

**Comment by tramyn** [comment]
Update: A warning dialog will appear when the user select Remove Association and it will display the SBOL id, displayId, and name of the SBOL object to be removed.
