### ISSUE TITLE
Need a cancel button for the associate SBOL prompt

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#359]
When no SBOL is associated, need a cancel button on the prompt that asks where you want to get the SBOL from.

**Comment by tramyn** [comment]
Update: The cancel button is now added and all dialog that support Associate SBOL will have this feature included. 

<img width="891" alt="associatesbol" src="https://cloud.githubusercontent.com/assets/7537729/26766635/f008837c-4952-11e7-9264-56708264f017.png">
