### ISSUE TITLE
Copy SBOL content into local library after model generation

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#360]
Need to loop through all six topLevel types (Seq, CD, MD, Model, GTL, Coll), check if TopLevel already in local SBOL document, if not add it, if is there, compare and report an error if they are not equal.

**Comment by tramyn** [comment]
Update: Feature is implemented and needs testing.

**Comment by cjmyers** [comment]
Looks good.  Closing.
