### ISSUE TITLE
Clicking on design in SBOL dialog should open it in SBOLDesigner 

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#370]
When you click on a design in the SBOL part selection dialog, it should open it in SBOLDesigner.

**Comment by tramyn** [comment]
@cjmyers This feature is now supported. This implementation assumes that the user can only click on one design to open in SBOLDesigner and the part selected is not a ModuleDefinition type.

**Comment by cjmyers** [comment]
Ok, can confirm it works for single CD, and does nothing as it should for MD.  Closing.
