### ISSUE TITLE
Update libSBML

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#392]
---------------------------------------
libSBML-5.15.2-experimental
----------------------------------------

We are pleased to announce the release of libSBML-5.15.2-experimental,
which is available for download from

https://sourceforge.net/projects/sbml/files/libsbml/5.15.2-experimental/

and as python-libsbml-5.15.2-experimental

=====================================================
5.15.2 (2017-07-27)
=====================================================

***                 Experimental only release                    ***

This is an experimental only release, that is, a release of those
files provided in the experimental folder of a full release.

This includes updates to all the SBML L3 packages that are not yet
accepted and undergoing development.

NOTE: An experimental release is not as rigorously tested as a
full release.  Any changes/fixes listed as either referring to
stable or experimental code may change before the next full release.

STABLE RELEASE

* New features

  There are no features in the stable branch; although there has
  been some optimization of code. We have also included testing
  of examples code in our test protocol.

* Bug fixes

  - Infix parsing of lambda functions was failing to consider
    variable names as variables, when they might overlap with
    other names for MathML constructs or csymbols e.g. 'time'
    or 'pi'. This has been corrected so that a lambda function
    will correctly produce the necessary <bvar> elements.

  - Conversion of interchangeable booleans and numbers was not
    reporting consistent information. This has been improved.

  - Conversion between SBML levels and versions was failing to
    correctly identify a speciesReference identifier. This is
    now sorted.

  - Sourceforge Tracker #8: The MATLAB bindings were failing to
    correctly convert logical functions. This has been fixed. Thanks
    to Fabian Froehlich for the report.

  - The check that reports <localParameters> shadowing other identifiers
    was not noticing when it shadowed a speciesReference.  This has
    been corrected.

  - The evaluateAST function was not correctly dealing with a
    missing math element.

  - 'comp' package-specific bug fixes:

    - Reading in externally referenced documents during 'comp'
      validation and/or flattening was consuming large amounts of memory.
      This has now been optimized.

    - There were some slight discrepancies with writing out the id
      attribute in an L3V2 document using 'comp' L3V1V1. These have
      been sorted out.

    - There was a very obscure endless loop in validation that
      Chris Myers managed to find. This is now closed. Thanks Chris.

  - 'groups' package-specific bug fixes:

    - Sourceforge libSBML Tracker #438: The C API for the plugin
      objects was missing. This has been corrected. Thanks to CJF for
      the report.

EXPERIMENTAL RELEASE

* New features

  - 'arrays' package-specific updates:

    - A basic ArraysFlatteningConverter has been added. As yet, this does
      not deal with arrays of submodels from the 'comp' package.

  - 'distrib' package-specific updates:

    - NOTE: the code has not been updated to the latest proposed version
      of the 'distrib' specification as this is currently under major
      review.

 * Bug fixes

  - 'arrays' package-specific bug fixes:

    - The 'arrays' code was not always correctly reading and writing the
      namespace. This has been fixed.

=====================================================

Please report any problems you encounter using libSBML either to the
mailing list libsbml-team@caltech.edu or using the issue tracker for
libSBML at

https://sourceforge.net/tracker/?group_id=71971&atid=942737

Thanks,

the LibSBMLTeam

**Comment by leandrohw** [comment]
Updated the README file to redirect people to the new version of libSBML
