### ISSUE TITLE
Check if Arrays code is valid in L3V1 or if L3V2 is required

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#397]
Need to ensure that we can use arrays in L3V1, and if not, then need to switch completely to L3V2 in 3.0 release.

**Comment by leandrohw** [comment]
Outside of a <functionDefinition>, if a <ci> element is not the first element within a MathML <apply>, then the <ci>'s value can only be chosen from the set of identifiers of <species>, <compartment>, <parameter>, <reaction>, or (in Level 3) <speciesReference> objects defined in the SBML model. (In L2V1, the <ci>'s value can't be chosen from the identifiers of <reaction> objects) (Reference: L3V1 Section 3.4.3).

**Comment by cjmyers** [comment]
So the problem with arrays is we use the id from the dimensions in ci terms?

**Comment by leandrohw** [comment]
Correct. We have this:
               <apply>
                  <selector/>
                  <ci> Time </ci>
                  <ci> d0 </ci>
                </apply>

**Comment by cjmyers** [comment]
It is not valid in L3V1, so we are moving to L3V2.
