### ISSUE TITLE
Updates in model do not get reflected in analysis view

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#400]
When the model is updated, the analysis view does not get updated with a new model for simulation.

**Comment by cjmyers** [comment]
This may actually be related to #402.  I think the model updates may be getting through but result is hidden since statistics not updated and also graph not updating.

**Comment by leandrohw** [comment]
Opened analysis view schematic, then changed model through model editor and the change was reflected in the analysis view.

**Comment by cjmyers** [comment]
I think the change is coming through, I think this is actually an issue with statistics not getting updated and graph not getting updated, so it appears as if the value did not change.

**Comment by cjmyers** [comment]
Works
