### ISSUE TITLE
Generating Model from analysis view gives error

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#403]
When I try to generate a model from the analysis view it produces an Error.  Likely there is a caught exception.

**Comment by cjmyers** [comment]
The problem is that it does not ask for a file name to save the model to.

**Comment by leandrohw** [comment]
Added communication between analysis and gui that allows user to select model id

**Comment by cjmyers** [comment]
This is working now.  Thanks.
