### ISSUE TITLE
Generating Network does not work

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#404]
When Network is selected, it does not open Graphviz:

Executing:
reb2sac.mac64 --target.encoding=dot --out=/Users/myers/Documents/Projects//GeneticToggleTutorial/GeneticToggle/GeneticToggle.dot /Users/myers/Documents/Projects//GeneticToggleTutorial/GeneticToggle/GeneticToggle.xml
Executing:
dotty nullnull.dot

**Comment by leandrohw** [comment]
Fixed commands called by Run when executing browser

**Comment by cjmyers** [comment]
Works
