### ISSUE TITLE
Delete not working in SBOL browser

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#406]
Cannot delete from SBOL browser window opened when you click on the SBOL document in the project.

**Comment by tramyn** [comment]
Update: It seems like getting the relative path to save the deleted SBOL component on the SBOL library file is pointing to the wrong location. To reproduce this error, create a new iBioSim project and import an SBOL design. Then open the SBOL library file and try to delete an SBOL component. When debugging, I am seeing that the path to the SBOL library file is pointing to the wrong SBOL library path.

**Comment by tramyn** [comment]
Update: I have added a warning dialog to indicate where the SBOL library file is located and what SBOL object will be deleted to help for UI debugging.

**Comment by cjmyers** [comment]
Seems to be working, please remove the debug.

**Comment by tramyn** [comment]
@cjmyers We need to revisit this bug. I found a way to reproduce this.

**Comment by cjmyers** [comment]
Ok, please document the steps to reproduce, so we can check on it.

**Comment by cjmyers** [comment]
Cannot reproduce, so perhaps fixed.
