### ISSUE TITLE
Problem when converting a GenBank file

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#421]
When converting a GenBank file to SBOL, using the converter, it throws this exception when trying to determine if it is an SBML file:

Exception in thread "main" java.lang.NullPointerException at
edu.utah.ece.async.ibiosim.dataModels.biomodel.util.SBMLutilities.isSBMLFile(SBMLutilities.java:286) at 
edu.utah.ece.async.ibiosim.conversion.Converter.main(Converter.java:273)`

Need to test the converter with SBML, SBOL, GenBank, and FASTA files.  Make sure that the SBML test is only done when the file is an XML file.  An XML file starts with "<".

**Comment by tramyn** [comment]
This issue was caused by appending text that was assumed as an xml format when checking if the input file is an SBML file. Now, if the file read is not of an xml format, the method will return false and continue on to GenBank conversion.
