### ISSUE TITLE
Dropping URI Prefix from VPR Model Generation

### ISSUE THREAD

**Issue by tramyn** [MyersResearchGroup/iBioSim#430]
After performing VPR model generation, the URI prefix for SBOL Interactions and additional SBOL components created from the VPR process are dropped. This dropping of information is performed when the output SBOLDocument produced from VPR process is converted to SBML. The SBOL annotations that is created on SBML Reactions, Models, ModifierSpeciesReference, and some Species are set to dummy URI prefixes.

To test this bug, I have recreated the genetic toggle switch by following the video tutorial that was uploaded on the SBOL Youtube account. The 3 SBML files that were translated from VPR model generation will show the dummy annotated prefix that are attached to the SBML elements mentioned.

**Comment by cjmyers** [comment]
Resolved by #455
