### ISSUE TITLE
Remove unnecessary namespaces on save

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#432]
Whenever you save or export should remove unnecessary namespaces.

**Comment by leandrohw** [comment]
Wrote a method in SBMLutilities.java to remove unused namespaces. However, the code assumes that a package is not used if the plugin is not set to any SBase in the document. This is a challenge because iBioSim creates the plugin to every SBase even if it is not used.

**Comment by leandrohw** [comment]
This has been fixed. I wrote helper functions to check if a plugin is used. This works on export. Particularly I don't know the reason to remove them on save since the internal state of the documents can be tool specific.

**Comment by cjmyers** [comment]
Looks good.  Closing.
