### ISSUE TITLE
Update to libsbml 5.16.0

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#442]
By the way:  it is suspicious to me that your error jumps in discrete chunks of 0.01 at 5 seconds, and every 10 seconds after that, with periodic decreases at multiples of 10 seconds.  The model itself doesn't do anything unusual at the 5-second marks, so it looks to me like the event might be failing to fire a single time at those time points.

The other thing is that your error trace looks identical for several different models, which I wouldn't expect from random errors, and all of the errors center around the multiples-of-5 data points.  (The requested output time points are slightly staggered from standard output--1001 steps over 100 seconds).

This is probably not an SBML interpretation issue, so I'm fine with leaving the model with a generous tolerance so you pass anyway.  But I suspect something is actually slipping at those points, as opposed to a general 'accumulation of error'.

-Lucian

**Comment by leandrohw** [comment]
README has been updated to reflect the new release.
