### ISSUE TITLE
Update analysis standalone to allow more arguments

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#449]
Analysis standalone should be able to take either a SED-ML file or a properties file.

It should also be able to take as arguments, all items on the main analysis view window.

Output should default to csv, with option to change on command line to tsd OR dat.

Instructions for building the standalone and running with the above arguments should be available on the README.

**Comment by cjmyers** [comment]
Needs some better defaults and error messages when it cannot find things.  Properties file load command should be documented.  Should assume current directory when looking for things.

**Comment by cjmyers** [comment]
Should be able to specify a results directory.

**Comment by leandrohw** [comment]
Implemented in e8ab157cd954432eb0c46b01002fce715ff35fc4
