### ISSUE TITLE
Standalone learn view (arguments, GeneNet, documentation)

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#450]
Should be able to execute GeneNet C++ from standalone.

Should be able to provide all the regular GeneNet arguments to this and the subset that the Java one understands.

Should be able to provide a levels file to specify levels.

Default output should be SBML with option to generate dot file instead.

README should include instructions for both building the standalone and running with the arguments above.

**Comment by leandrohw** [comment]
Done with #468 and #470
