### ISSUE TITLE
reb2sac and GeneNet should be found on the path instead of specified by name

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#451]
Calls to reb2sac and GeneNet should be machine independent and find the program on the path instead of specified location.

**Comment by cjmyers** [comment]
Now looks for these on the path and pops up a window if functioning ones cannot be found on the path.  One can decide to ignore this which sets a preference and stops the window popping up.  Message still goes to console.  

@leandrohw let me know if this works for you.  Also, this means updating GeneNet/reb2sac and iBioSim install instructions to make this work.

**Comment by cjmyers** [comment]
I've changed iBioSim to find reb2sac/GeneNet in the path rather than specified by OS in the bin directory.  Please test. @tramyn @leandrohw

**Comment by leandrohw** [comment]
Worked fine. Closing this one.
