### ISSUE TITLE
Move the binaries for reb2sac/GeneNet to the release for these programs

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#452]
The binaries should be added to the releases for reb2sac/GeneNet and not checked in to github.

**Comment by leandrohw** [comment]
Created releases for reb2sac and GeneNet. Added pre-compiled binaries for mac and windows. However, iBioSim is not referencing these releases. iBioSim releases already package everything.

**Comment by cjmyers** [comment]
I tried the windows install last night and reb2sac actually worked.  My guess is that differences will likely be due to missing libraries.  Probably to debug on a machine that is not working need to do like I did on Mac and run each command individually then see what reb2sac says when you try to run it.  However, with the addition of the missing library for the Mac version, perhaps we will just go ahead and release.

**Comment by cjmyers** [comment]
@tramyn let us know if reb2sac works on your windows machine.
