### ISSUE TITLE
Prompt user to enter domain if it is still set to the default domain

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#455]
If domain is http://dummy.org in preferences, ask the user to change it.

**Comment by cjmyers** [comment]
Now when domain is set to dummy.org when you start iBioSim, it gives a warning that you need to change this, and then pops up the preferences, so you can change this. 

@tramyn let me know if this addresses your concern.

**Comment by tramyn** [comment]
@cjmyers Tested and is working as described.
