### ISSUE TITLE
setObjectType called in the Gui class is undefined

### ISSUE THREAD

**Issue by zgzn** [MyersResearchGroup/iBioSim#486]
My code is up to date with the master branch. But I have this error. See attached screenshot.

<img width="1357" alt="screen shot 2018-01-19 at 2 35 57 pm" src="https://user-images.githubusercontent.com/7920249/35188756-29f25864-fdf9-11e7-95a6-8b075b51aade.png">

**Comment by cjmyers** [comment]
Have you updated and built SBOLDesigner?  These method was added to that code fairly recently.

**Comment by zgzn** [comment]
I just did. It fixed this error. Thanks.
