### ISSUE TITLE
editPart call in the gui class has mismatched arguments

### ISSUE THREAD

**Issue by zgzn** [MyersResearchGroup/iBioSim#487]
After updating SBOLDesigner, iBioSim, and libSBOLj, and maven builds for them, this error still shows up. See attached screenshot. 
<img width="1424" alt="screen shot 2018-01-20 at 8 04 24 pm" src="https://user-images.githubusercontent.com/7920249/35190415-3848c680-fe1e-11e7-889a-905308ffacf8.png">

**Comment by cjmyers** [comment]
Sorry I found this one last night but forgot to checkin.  It should be fixed now.  Michael changed this function recently in SBOLDesigner.

**Comment by zgzn** [comment]
Works now. Thanks.
