### ISSUE TITLE
Missing component reb2sac

### ISSUE THREAD

**Issue by jakebeal** [MyersResearchGroup/iBioSim#498]
I just downloaded the latest release of iBioSim for Mac, and when I launched it, it complained it was missing a component "reb2sac"

**Comment by cjmyers** [comment]
That is a C-based simulation tool.  If you are either not doing simulation or are satisfied using our Java-based simulators, you can ignore this issue.

However, this is a bug in the release as reb2sac does come pre-compiled for Mac.  Thanks for pointing this out.  We will try to get it sorted.

**Comment by cjmyers** [comment]
@leandrohw I can reproduce this.  I ran each step of the iBioSim.mac64 script, then tried to run reb2sac.  Here is the message I get:

dyld: Library not loaded: /usr/local/lib/libxml2.2.dylib
  Referenced from: /Users/myers/Downloads/iBioSim-mac/bin/./reb2sac
  Reason: Incompatible library version: reb2sac requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
Abort trap: 6

**Comment by leandrohw** [comment]
Strange. reb2sac should have used libxml2 in the lib directory, not in your /usr/local/bin.

**Comment by cjmyers** [comment]
The message is indeed strange as libxml2.2.dylib is in my /usr/lib directory.  However, I suspect that is the one it is trying to use.  However, my guess is you compiled this with a later version and it is complaining that my version is too old.  This is why I hate dynamically linked libraries.  

We could perhaps package the later version libxml2.2 in the lib directory that we include, but I’m afraid that there may be other issues about wrong versions of libraries.  

BTW: I wonder if this also explains the Windows issues with reb2sac, namely that people have different versions of libxml2.2.  

Perhaps the only solution is to see if we can create a static build of reb2sac.  I will poke around on this and see if I can figure out anything.

**Comment by cjmyers** [comment]
I obtained the latest libxml2 and copied it to the lib directory, and this seems to have fixed reb2sac

**Comment by jakebeal** [comment]
Works for me now.
