### ISSUE TITLE
Can't open SBOLDesigner

### ISSUE THREAD

**Issue by jakebeal** [MyersResearchGroup/iBioSim#499]
Latest release on Mac:

Select designs -> "Open SBOLDesigner"

Response: "you need to open SBOL Designer"
(in uncopyable error dialogue)

**Comment by cjmyers** [comment]
I see the problem with this one, I think.  It got introduced trying to make the window come in front.  I will try to sort it out tomorrow.  Thanks for catching this.

**Comment by cjmyers** [comment]
This issue should be sorted now in master and will be fixed in the next build, which I will make once I have taken a shot at sorting the reb2sac issue.

**Comment by jakebeal** [comment]
Works for me now.
