### ISSUE TITLE
Improve Markov analysis options?

### ISSUE THREAD

**Issue by zgzn** [MyersResearchGroup/iBioSim#515]
It is not quite clear what the reachability-analysis does. Also the ctmc-transient generated the errors below. I think options for Markov analysis should be re-organized and each option's function should be explained a bit more (either in the analysis view or in a separate tutorial document). 

Executing:
reb2sac --target.encoding=ctmc-transient --reb2sac.properties.file=/Users/zhangz/research/lpn/genetic_circuits//stochastic_model_checking/dual_feedback_oscillator/dual_feedback_oscillator.properties /Users/zhangz/research/lpn/genetic_circuits//stochastic_model_checking/dual_feedback_oscillator/dual_feedback_oscillator.xml

Errors:
species P1 cannot be used in CTMC
 :  : 	failed to transform IR to CTMC

Total Simulation Time: 0.207091775 seconds

**Comment by cjmyers** [comment]
Hmm, not sure the stability of the methods in reb2sac for transient analysis.  We moved to use the ones in Java.

**Comment by zgzn** [comment]
Maybe mark it as "deprecated" or "experimental" so that users know to use to right CTMC analyzer. Also, what is the purpose of the "reachability analysis"? It does not seem to invoke any analyzer now.

**Comment by cjmyers** [comment]
Need to double check with Leandro on how this got refactored.

**Comment by leandrohw** [comment]
Disabled reachability-analysis, atacs, and ctmc-transient.
