### ISSUE TITLE
Progress bar not working in Markov analysis

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#516]
Markov has to be an observable object and notify the objects observing it when there is an update. Whenever a markov object is created, it needs to register Run as a parent. This is how reb2sac updates the progress bar:

this.message.setInteger(prog);
parent.send(RequestType.REQUEST_PROGRESS, message);

**Comment by leandrohw** [comment]
Fixed

**Comment by cjmyers** [comment]
Works
