### ISSUE TITLE
Threshold 0 causes error in the generated PRISM model

### ISSUE THREAD

**Issue by zgzn** [MyersResearchGroup/iBioSim#520]
When specifying 0 as an interesting threshold, the generated PRISM model contains an expression with divide-by-0, which causes PRISM CTMC analysis to fail. To reproduce this, download stochastic_model_checking.zip attached to bug #519. If you specify 0 for either LacI or TetR in the attached toggle_switch.xml, you can produce such an expression in the generated prism file.

**Comment by cjmyers** [comment]
As we discussed in our call, 0 should never be set as a threshold, since it is always one by default.  However, this should be explicitly disallowed to prevent the error you found.

**Comment by zgzn** [comment]
Yes. The allowed threshold should be a positive integer.

**Comment by cjmyers** [comment]
Now disallows 0.
