### ISSUE TITLE
Browser and Network options always disabled in Analysis Type in Analysis view in iBioSim GUI

### ISSUE THREAD

**Issue by thakurneupane** [MyersResearchGroup/iBioSim#521]
Browser and Network options are always disabled in Analysis Type in Analysis view in iBioSim GUI.
OS: Windows 10, Debian GNU/Linux 9
![browser_1](https://user-images.githubusercontent.com/35314579/38954107-063f92ce-430e-11e8-8c79-e15dd844ff33.png)
![browser_2](https://user-images.githubusercontent.com/35314579/38954115-0aae930a-430e-11e8-92eb-f321c43fa820.png)

**Comment by cjmyers** [comment]
The reason for this is the “reb2sac” program is not found.  You should download and install this program.  See the section on building reb2sac here:

https://github.com/MyersResearchGroup/iBioSim <https://github.com/MyersResearchGroup/iBioSim>
