### ISSUE TITLE
Add support to give an id to the top-level of a model generation

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#524]
When a user selects more than one CD to run VPR model generation on, provide a prompt to ask for the Id of the top-level model.  Then, call the VPR using the new API:

SBOLInteractionAdder_GeneCentric interactionAdder=new SBOLInteractionAdder_GeneCentric(URI.create(endpoint),"newDesign");

**Comment by tramyn** [comment]
@cjmyers, this feature has been added and tested. If you would like to verify, you can checkout the latest master branch. You can also close this issue if you are satisfied with this change.

**Comment by cjmyers** [comment]
This works well.
