### ISSUE TITLE
Expression Parsing error in LPN models

### ISSUE THREAD

**Issue by thakurneupane** [MyersResearchGroup/iBioSim#525]
delay_assignments expression in LPN models are incorrectly parsed.
Expr1 = exponential(0.5\***(AraC^2.0)**+0.2)
Expr2 = exponential(0.5*AraC^2.0+0.2)

Expr1 and Expr2 are being evaluated to different values for same AraC. In Expr2, the operator **^** is incorrectly applied to **0.5**.

[FSG_(0.5*(AraC^2.0)+0.2).pdf](https://github.com/MyersResearchGroup/iBioSim/files/1989383/FSG_.0.5.AraC.2.0.0.2.pdf)
[FSG_(0.5*AraC^2.0+0.2).pdf](https://github.com/MyersResearchGroup/iBioSim/files/1989384/FSG_.0.5.AraC.2.0.0.2.pdf)
[TestParsing_lpn.txt](https://github.com/MyersResearchGroup/iBioSim/files/1989388/TestParsing_lpn.txt)

**Comment by zgzn** [comment]
This has been fixed in the LPN parser.
