### ISSUE TITLE
Running iBioSim on Mac with High Sierra OS and the latest Java. I tried to import the SynBioTutorial file for test 01195 and got the following error:

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#530]
iBioSim Version 3.0.0-beta

Operating system: Mac OS X

Bug reported by: kclancy@syntheticgenomics.com

Description:
Imported SED-ML file contains the errors listed below. It is recommended that you fix them before performing this analysis or you may get unexpected results.

0:cvc-elt.1.a: Cannot find the declaration of element 'sedML'.
1:cvc-elt.1.a: Cannot find the declaration of element 'sedML'.
2:cvc-elt.1.a: Cannot find the declaration of element 'sedML'.

**Comment by cjmyers** [comment]
This works for me.  Which file were you trying to import?

**Comment by cjmyers** [comment]
Cannot reproduce.  Closing.
