### ISSUE TITLE
Unable to upload a saved iBioSim project

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#532]
iBioSim Version 3.0.0-beta

Operating system: Mac OS X

Bug reported by: kclancy@syntheticgenomics.com

Description:
I built a iBioSim project based upon the tutorial. I saved it and closed iBioSim.
When I returned to iBioSim I attempted to open the saved project using File-> Open Project. None of the project files are recognised as input by iBioSim. 
What do I do next - is this a bug?

**Comment by MadraghRua** [comment]
If it helps I can provide you the project I am working with.

**Comment by cjmyers** [comment]
My suspicion is you are trying to open files and not projects.  A project is a directory, and you should be selecting a directory to open.  Can you confirm you are selecting the project directory to open?
