### ISSUE TITLE
iBioSim deleted my files 

### ISSUE THREAD

**Issue by banglajihwan** [MyersResearchGroup/iBioSim#533]
iBioSim removed all my files in the Desktop. 
I tried to make a new project. 
File -> New -> Project. 
A new window called 'New" popped up. I selected my Desktop folder thinking that a new file would be made in the folder that I specify. I clicked the 'New' button. 
Another window popped up saying that the 'file' already exist and saying whether I wanted to overwrite. 
I was bit confused at this point, because I didn't make any files. So, I just clicked overwrite. 
Then all my files in the Desktop got deleted. I now have to remember whether there were any important files that are missing. I usually don't save important files on my desktop so I believe it's okay. It's my mistake, but I think there can be measures to prevent this from happening for other people. 

First, there needs to be measure to prevent iBioSim changing existing folders. 
I think the nomenclature can improve to minimize confusion. For example, the second pop up window should say 'folder' not file if it is saying there is an existing folder. The new button in the first pop up is bit confusing too, maybe saying 'create' can be better.

**Comment by cjmyers** [comment]
I'm so sorry about that.   Do you think if it said "folder" you would have realized?  

Trouble is sometimes you do want to overwrite existing projects, which means overwrite existing folders.  Not sure how to know when it is and is not a folder you care about.  Maybe we need a second warning or a more striking warning that says something stronger to get your attention. 

Again, sorry about this.  Hope you did not lose anything important and have a backup, if you did.

**Comment by banglajihwan** [comment]
I think if it said "folder", it could have helped. 
Maybe a warning that says overwriting an existing folder can delete all files can help.

**Comment by cjmyers** [comment]
How's this?

![screen shot 2018-06-11 at 9 20 29 am](https://user-images.githubusercontent.com/3507191/41240843-b6e77a5a-6d58-11e8-8a4f-2a3f3be72b21.png)

**Comment by cjmyers** [comment]
Note that Cancel is also now the default option.
