### ISSUE TITLE
Arrays simulator is not working

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#539]
Arrays simulator does not seem to be working even for simple examples, like reversing rule assignments.

**Comment by cjmyers** [comment]
Works for stochastic but did not work for runge-kutta on the attached model
[ArraysTest.zip](https://github.com/MyersResearchGroup/iBioSim/files/2342926/ArraysTest.zip)

**Comment by leandrohw** [comment]
Arrays wasn't actually implemented in the ODE simulator. It works for the example now.

**Comment by cjmyers** [comment]
Looks good
