### ISSUE TITLE
Unable to set a NOT boolean expression

### ISSUE THREAD

**Issue by tramyn** [MyersResearchGroup/iBioSim#550]
I have a model that has a Boolean variable v0. I tried creating a transition with a trigger condition set to !v0 and I got this message, "Argument for not function must be of type Boolean".

<img width="605" alt="trigger_condition" src="https://user-images.githubusercontent.com/7537729/44554749-6368b080-a6ef-11e8-86d6-c773d1c39a99.png">

**Comment by cjmyers** [comment]
@tramyn should be fixed in master.  Please test.

**Comment by tramyn** [comment]
I can confirm that this issue is resolved with the latest update to iBioSim.
