### ISSUE TITLE
Problem with libsbml flatten for the attached project

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#554]
[TramyTest.zip](https://github.com/MyersResearchGroup/iBioSim/files/2349380/TramyTest.zip)

**Comment by tramyn** [comment]
A fix was made to commit: edac513c3289482211bf943ae0717ecbe752e9d7

**Comment by cjmyers** [comment]
I had to revert this change.  The problem is the "filename" passed to load actually is a full path in iBioSim.  You were sending just the filename.  So, when you make this change, now a simple file name is fine but it breaks iBioSim which sends a full path.  Please try your code with a full file path sent to load method.

**Comment by leandrohw** [comment]
I don't think it would work. The way flattening in BioModel is setup is a bit strange because it saves filename_temp but it tries to load path+filename_temp.

**Comment by cjmyers** [comment]
Strange.  The change you made though broke it within the GUI.

**Comment by tramyn** [comment]
This issue has been resolved without having to modify the BioModel. I can get the compiler to work without having to make any necessary changes from iBioSim.
