### ISSUE TITLE
Analysis jar does not use properties file

### ISSUE THREAD

**Issue by Oliver-OBrien** [MyersResearchGroup/iBioSim#569]
When running the analysis jar as described in the README, the -p argument does not seem to actually load a properties file. Regardless of the contents of the file specified, it will be overwritten when the command completes. The new properties file depends on the command line arguments and seems to contain the properties that were actually used.

**Comment by cjmyers** [comment]
I just checked into the master branch what I think is a fix to this issue.  Please test and let us know.

**Comment by Oliver-OBrien** [comment]
The fix works, properties files are now being used as expected.
