### ISSUE TITLE
Update libsbml

### ISSUE THREAD

**Issue by cjmyers** [MyersResearchGroup/iBioSim#571]
---------------------------------------
libSBML-5.17.2-experimental
----------------------------------------

We are pleased to announce the release of libSBML-5.17.2-experimental,
which is available for download from

https://sourceforge.net/projects/sbml/files/libsbml/5.17.2-experimental/

and as python-libsbml-5.17.2-experimental

====================================================================
5.17.2-experimental (2018-12-06)
====================================================================

***                 Experimental only release                    ***

This is an experimental only release, that is, a release of those
files provided in the experimental folder of a full release.

This includes updates to all the SBML L3 packages that are not yet
accepted and undergoing development.

NOTE: An experimental release is not as rigorously tested as a
full release.  Any changes/fixes listed as either referring to
stable or experimental code may change before the next full release.

STABLE RELEASE

* New features

   - The math code has been refactored to use the more efficient
     math-legacy code in combination with a math plugin system.
     This code has been optimized and we welcome feedback on any
     performance issues.  This means there is no longer a math-legacy
     build option.

   - The new math constructs introduced in SBML L3V2 have been refactored
     as a math extension; which facilitates the use of these math functions
     in an SBML L3V1 document.

   - 'comp' package-specific updates:

     - The 'comp' specification states that an external model must be
       an L3V1 document. Since this specification predates SBML L3V2
       we have relaxed the restriction to allow an L3V2 model using
       Model Composition to use an L3V2 external model.

     - The converter that 'flattens' a comp model has been optimized
       for speed with significant improvement for larger models.

   - Python interface specific updates:

     - In libSBML the set/add/unset methods return a code to indicate
       success or failure of the operation. The Python interface has
       been improved to produce a warning when a function fails. This
       behavior can be enabled by setting a CMAKE configure option
       or an environment variable.

     - Sourceforge Tracker item #456: The Python interface has
       been changed to return an empty List of CVTerms rather
       than a None object.

     - Users have raised issued about Model objects retrieved from 
within an
       SBMLDocument object going out of scope when the document object
       is removed from scope. We have adjusted the code to allow a Model
       to remain in scope without it's parent document. Feedback would
       be appreciated about whether this is sufficient or whether all child
       objects should be available regardless of whether their parent is
       still available.

     - Sourceforge Tracker item #468:  Functions deprecated in Python 3.6
       have been replaced to avoid deprecation warning messages.

* Bug fixes

   - The function SBMLTypeCode_toString was not retuning the correct
     string for a ListOf element originating in a package. This
     has been corrected.

   - Using an SBML L3 package in an L2 document could cause a crash.
     This has been fixed. Thanks to Thomas Hamm for reporting it.

   - The code that checked for use of an L3V2 package with an L3V1
     document could cause a crash. This has been fixed.

   - Writing out a document without a model and no level and version
     was using level = version = 0; which is not valid. This has been
     changed to write a L3V2 document with no model.

   - There was an issue with newer architectures when casting a
     NaN to an integer - this has been now been avoided.

   - MATLAB interface specific bug fixes:

     - The matlab binding was failing to distinguish between a
       functionDefinition where the id ended with a logical operator,
       e.g. 'myor' and the actual logical function. This has been 
corrected.

   - 'comp' package-specific bug fixes:

     - There was an issue with flattening 'comp' models using conversion
       factors. This has been tracked down and fixed. Thanks to Matthias
       Konig for reporting it and providing examples.

   - 'render' package-specific bug fixes:

     - Historical render code did not create a NULL BoundingBox.
       Current code has been brought in line with this.

* Configuration/build system changes

   - Python 3.7 is now supported and included in the builds.

   - The USE_LEGACY_MATH option has been removed as code has been
     reverted to use this math implementation (see above).

EXPERIMENTAL RELEASE

* New features

   - 'distrib' package-specific updates:

     - The distrib package code has been updated to include the use
       of csymbols to reference distributions. This is in line with
       the latest distrib specification.

=====================================================

Please report any problems you encounter using libSBML either to the
mailing list libsbml-team@googlegroups.com or using the issue tracker for
libSBML at

https://sourceforge.net/tracker/?group_id=71971&atid=942737

Thanks,

the LibSBMLTeam

-- 
You received this message because you are subscribed to the Google Groups "sbml-discuss" group.
To unsubscribe from this group and stop receiving emails from it, send an email to sbml-discuss+unsubscribe@googlegroups.com.
To post to this group, send email to sbml-discuss@googlegroups.com.
To view this discussion on the web visit https://groups.google.com/d/msgid/sbml-discuss/51a41392-4f0f-3f79-a8d6-4ac8f38f7300%40caltech.edu.
For more options, visit https://groups.google.com/d/optout.

**Comment by LukasBuecherl** [comment]
Issue #579 is about updating libsbml to 5.18.0 making this issue obsolete.
