### ISSUE TITLE
Add citation information for iBioSim

### ISSUE THREAD

**Issue by zgzn** [MyersResearchGroup/iBioSim#598]
It would be nice to mention a most recent paper on iBioSim, including the bibliography information, on its homepage for people to cite in their publications. As an example, this is what PRISM does: https://www.prismmodelchecker.org/.

**Comment by ballaneypranav** [comment]
Hey, I'd like to work on this, but this will go on the website at https://async.ece.utah.edu/tools/ibiosim/ right? Is the website being built out of this repo?

**Comment by cjmyers** [comment]
Actually, we would like to migrate it to github.io here:

https://myersresearchgroup.github.io/ibiosim.github.io/

where the source is here:

https://github.com/MyersResearchGroup/ibiosim.github.io

Are you interested in working on iBioSim documentation?

**Comment by ballaneypranav** [comment]
Yes, definitely. I noticed that there are some issues raised on the documentation repository about installation instructions, so maybe I could start by submitting PRs for those, along with the citation information?

**Comment by cjmyers** [comment]
Sure.  That is helpful.  Thanks.
