### ISSUE TITLE
Manual option from drop-down menu in iBioSim broken

### ISSUE THREAD

**Issue by Fontanapink** [MyersResearchGroup/iBioSim#599]
When clicking on the Manual option from the iBioSim GUI:

![image](https://user-images.githubusercontent.com/12236668/78031800-6cdde400-733a-11ea-8c3b-f15e5a90e448.png)

It opens a broken link:

![image](https://user-images.githubusercontent.com/12236668/78031895-8d0da300-733a-11ea-9472-5b4791f8af1f.png)

**Comment by cjmyers** [comment]
Committed fix, please test @Fontanapink

**Comment by Fontanapink** [comment]
Working fine now thank you
