### ISSUE TITLE
reb2sac on macOS Catalina 10.15.4

### ISSUE THREAD

**Issue by criera90** [MyersResearchGroup/iBioSim#602]
I've been using iBioSim for one of my classes. When I try to use the iBioSim in the top directory, it doesn't work. I've been able to run it on my MacBook (Catalina 10.15.4) by double click in the iBioSim.jar located in the ibiosim/bin directory. However, every time I initialize the application a message appears:

****
WARNING: Some external components are missing or have problems. You may continue but with some loss of functionality. Lbsbml not found (UnsatisfiedLinkError)
Reb2sac not found
GeneNet not found
****

I'm not sure if this would prevent me to use some functionalities. I've been able to model using ODE but I only see the Runge-Kutta methods. I hope you could help.

Thanks.

**Comment by criera90** [comment]
I tried downloading it again. It looks like the first time I installed iBioSim 3.0.0.0 MacOS didn't allow to execute some libraries and I din't manually changed the security permissions in System preferences using "Open anyway" in the Security and Privacy menu.

**Comment by cjmyers** [comment]
Looks like you sorted this.  One more key aspect is that you should be running the iBioSim.mac64 script to start things up, which will enable you to see the other programs (reb2sac, GeneNet, etc.).  Assuming that you have installed them.

**Comment by criera90** [comment]
> Looks like you sorted this. One more key aspect is that you should be running the iBioSim.mac64 script to start things up, which will enable you to see the other programs (reb2sac, GeneNet, etc.). Assuming that you have installed them.

When I double click in the iBioSim.mac64 script it shows this: 
****
There is no application set to open the document “iBioSim.mac64” 
****

Should I be using the terminal?

**Comment by cjmyers** [comment]
Yes try the terminal

Chris

**Comment by criera90** [comment]
> Yes try the terminal Chris
> […](#)

It worked! 

Although showed the same message as if I used the "iBioSim" executable form the top menu:

***
/Users/crieraruiz/AAA/iBioSim-mac64/bin/..
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by edu.utah.ece.async.ibiosim.gui.util.OSXHandlers (file:/Users/crieraruiz/AAA/iBioSim-mac64/bin/iBioSim.jar) to constructor com.apple.eawt.Application()
WARNING: Please consider reporting this to the maintainers of edu.utah.ece.async.ibiosim.gui.util.OSXHandlers
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
***

Carlos

**Comment by cjmyers** [comment]
Interesting.  I've not seen that warning before, but I think I know where it is coming from.  It should not affect anything, but let us know if you run into any other issues.

**Comment by criera90** [comment]
Will do, thank you a lot!

Carlos
