### ISSUE TITLE
Reaction SBO Terms dropped on Editor Reopening

### ISSUE THREAD

**Issue by Paytonco** [MyersResearchGroup/iBioSim#617]
If a local parameter is added to a reaction and assigned an SBO term, that SBO term is deleted upon reopening the reaction editor in the UI.  Note that the SBO term is assigned properly and will 'stick' so long as the reaction editor is not opened again.

**Comment by cjmyers** [comment]
@Paytonco can you update and test if this is now working.

**Comment by Paytonco** [comment]
It is working correctly now
