### ISSUE TITLE
BUG: layout arrays are not stripped out when arrays are removed
 from the model

### ISSUE THREAD

**Issue by buggsley** [MyersResearchGroup/iBioSim#99]
When you create an arrayed object such as species and you remove the arrays=
, layout remains an array even though the object is not an array anymore.

**Comment by buggsley** [comment]
Remove arrays from layout, since they are not very meaningful.  However, this
means that array flattening 
MUST remove layout first.

**Comment by cjmyers** [comment]
I think this is being done.  Please check.
